[global/wm]
margin-top 			= 0
margin-bottom 			= 0

[settings]
pseudo-transparency 		= true 
;transparent = #00000000 pseudo-transparency = true

;-_-_-_-_-_-_-_ -_-_-_-_-_-_-_ -_-_-_-_-_-_-_ -_-_-_-_-_-_-_ -_-_-_-_-_-_-_
include-file 			= $POLYBAR/blocks/modules.ini
include-file 			= $POLYBAR/blocks/colors.ini
include-file 			= $POLYBAR/blocks/dwm.ini
;-_-_-_-_-_-_-_ -_-_-_-_-_-_-_ -_-_-_-_-_-_-_ -_-_-_-_-_-_-_ -_-_-_-_-_-_-_
[bar/main]
bottom 				= false 
enable-ipc 			= true
height 				= 50
width 				= 99%
offset-x			= .5%
border-size 			= 15
;border-color 			= #00000000

font-0				= LigaSFMonoNerdFont:size=10;3
cursor-click 			= pointer
background 			= #00000000 
;background 			= #ffffff


;Encloser Left
[module/E1]
type 				= custom/text
content 			= "[" 
content-background		= ${colors.primary}
content-foreground		= ${colors.secondary}
;content-padding= 2

;Encloser Right
[module/E2]
type 				= custom/text
content 			= "]" 
content-background		= ${colors.primary}
content-foreground		= ${colors.secondary}
;content-padding= 2



[module/space]
type 				= custom/text
content-background		= ${colors.primary}
content 			= "    "

[module/spaceN]
type 				= custom/text
content-background		= #00000000
content 			= "    "	


[bar/bar1]
monitor 			= ${env:MONITOR:}
inherit 			= bar/main
modules-left 			= space dwmMenu space spaceN  space dwmTitle space 

modules-right 			= space E1 netI netT E2 E1 tempI tempT E2 E1 memoryI memoryT E2 E1 diskI diskT  E2 E1 volumeI volumeT  E2 E1 brightnessI brightnessT E2 E1 batteryI batteryT E2 E1 dateI dateT E2 space




; vim:ft=dosini

