[colors]
primary 		= #1A1A1A
secondary 		= "#fbf1c7"
alert 			= ${xrdb:color1}
background-alt 		= ${xrdb:color2}
focused 		= ${xrdb:color3}
unfocused 		= ${xrdb:color3}
icon 			= ${xrdb:color5}


; vim:ft=dosini

