
[module/dwmMenu]
type 				= internal/dwm
format 				= <label-tags> 
;format-foreground 		= ${colors.secondary}

;focused
label-focused 			= %name%
label-focused-background 	=#3D436A 
label-focused-foreground 	= ${colors.primary}
label-focused-padding 		= 0

; unfocused = Unselected tag on unselected monitor
label-unfocused 		= %name%
;label-unfocused-background 	= ${colors.primary}	
label-unfocused-foreground	= #3D436A
label-unfocused-padding 	= 0

; visible = Unselected tag, but occupied tag on any monitor 
label-visible 			= %name%
label-visible-background 	= ${colors.primary}
label-visible-foreground	= #E56516

; urgent  Unselected tag with window that has urgency hint set
label-urgent 			= %name%
label-urgent-background 	= ${colors.secondary}
label-urgent-foreground 	= ${colors.primary}
label-urgent-padding 		= 0

; empty = Unselected and unoccupied tag
; This can be set to an empty string to hide empty tags
;label-empty 			= %name%
;label-empty 			= ""
label-empty-background 		= ${colors.primary}

label-empty-foreground	= #3D436A 

;;Bar Custom Settings
enable-tags-click 		= true
enable-tags-scroll 		= true
tags-scroll-empty 		= false
tags-scroll-reverse 		= true 
tags-scroll-wrap 		= true
enable-layout-click 		= true
enable-layout-scroll 		= true
layout-scroll-wrap 		= true 
layout-scroll-reverse 		= true

[module/dwmTitle]
type 				= internal/dwm
format 				= <label-title>
label-title-radius 		= 20
label-title 			= %title%
label-title-foreground 		= ${colors.secondary}
label-title-background		= ${colors.primary}
label-title-maxlen 		= 50

; vim:ft=dosini
