[scripts]
temp 				= ". ${POLYBAR}/scripts/variables temprature"
ram 				= ". ${POLYBAR}/scripts/variables memory"
updates 			= ". ${POLYBAR}/scripts/variables updates"
net				= ". ${POLYBAR}/scripts/variables net"
disk 				= ". ${POLYBAR}/scripts/variables disk"
date 				= ". ${POLYBAR}/scripts/variables date"
volume 				= ". ${POLYBAR}/scripts/variables volume"
brightness 			= ". ${POLYBAR}/scripts/variables brightness"
battery 			= ". ${POLYBAR}/scripts/variables battery"
;-_-_-_-_-_-_-_ -_-_-_-_-_-_-_ -_-_-_-_-_-_-_ -_-_-_-_-_-_-_ -_-_-_-_-_-_-_
[bar/icon]
type 				= custom/text
content-background 		= ${colors.primary}
content-padding 		= 1
content-foreground		=${colors.secondary}


[bar/text]
type 				= custom/script
;;interval 			= ${const.interval_5}
format-background 		= ${colors.primary}
format-foreground		= ${colors.secondary}
format-padding 			= 1
click-right 			= st -e nvim ${POLYBAR}/bar#2/scripts

;-_-_-_-_-_-_-_ -_-_-_-_-_-_-_ -_-_-_-_-_-_-_ -_-_-_-_-_-_-_ -_-_-_-_-_-_-_
[module/tempI]
inherit 			= bar/icon
content 			= "" 
;content-foreground 		= ${xrdb:color1}

[module/tempT]
inherit 			= bar/text
exec 				= ${scripts.temp}
click-left 			= st -e btop
click-middle 			= st -e radeontop -c 
;-_-_-_-_-_-_-_ -_-_-_-_-_-_-_ -_-_-_-_-_-_-_ -_-_-_-_-_-_-_ -_-_-_-_-_-_-_
[module/memoryI]
inherit 			= bar/icon
content 			= "" 
;content-foreground 		= ${xrdb:color2}

[module/memoryT]
inherit 			= bar/text
exec 				= ${scripts.ram}
click-left 			= st -e btop
click-middle 			= st -e radeontop -c 
click-right 			= st -e nvim ~/.config/polybar/scripts/ram
;-_-_-_-_-_-_-_ -_-_-_-_-_-_-_ -_-_-_-_-_-_-_ -_-_-_-_-_-_-_ -_-_-_-_-_-_-_
[module/netI]
inherit 			= bar/icon
content 			= "" 
;content-foreground 		= ${xrdb:color3}


[module/netT]
inherit 			= bar/text
exec 				= ${scripts.net}
click-left 			= st -e nmtui
;-_-_-_-_-_-_-_ -_-_-_-_-_-_-_ -_-_-_-_-_-_-_ -_-_-_-_-_-_-_ -_-_-_-_-_-_-_
[module/dateI]
inherit 			= bar/icon
content 			= ""  
;content-foreground 		= ${xrdb:color4}


[module/dateT]
inherit 			= bar/text
type 				= internal/date
interval 			= 60
date 				= %H:%M
time 				= %H:%M
date-alt 			= %A, %d %B %Y
time-alt 			= %H:%M:%S
;-_-_-_-_-_-_-_ -_-_-_-_-_-_-_ -_-_-_-_-_-_-_ -_-_-_-_-_-_-_ -_-_-_-_-_-_-_
[module/diskI]
inherit 			= bar/icon
content 			= "" 
;content-foreground 		= ${xrdb:color5}


[module/diskT]
inherit 			= bar/text
exec 				= ${scripts.disk}
;-_-_-_-_-_-_-_ -_-_-_-_-_-_-_ -_-_-_-_-_-_-_ -_-_-_-_-_-_-_ -_-_-_-_-_-_-_
[module/volumeI]
inherit 			= bar/icon
content 			= " " 
;content-foreground 		= ${xrdb:color6}


[module/volumeT]
inherit 			= bar/text
exec 				= ${scripts.volume} 
click-left 			= st -e alsamixer
scroll-up 			= amixer -qc 1 set Master 5%+
scroll-down 			= amixer -qc 1 set Master 5%- 
;-_-_-_-_-_-_-_ -_-_-_-_-_-_-_ -_-_-_-_-_-_-_ -_-_-_-_-_-_-_ -_-_-_-_-_-_-_
[module/brightnessI]
inherit 			= bar/icon
content 			= ""
;content-foreground 		= ${xrdb:color3}


[module/brightnessT]
inherit 			= bar/text
exec 				= ${scripts.brightness}
scroll-up 			= sudo xbacklight -inc 10
scroll-down 			= sudo xbacklight -dec 10
;-_-_-_-_-_-_-_ -_-_-_-_-_-_-_ -_-_-_-_-_-_-_ -_-_-_-_-_-_-_ -_-_-_-_-_-_-_
[module/batteryI]
inherit 			= bar/icon
content 			= "" 
;content-foreground 		= ${xrdb:color10}

[module/batteryT]
inherit 			= bar/text
exec 				= ${scripts.battery}
; vim:ft=dosini

