[colors]
primary 		= "#2D4451"
secondary 		= "#FD7459"
alert 			= ${xrdb:color1}
background-alt 		= ${xrdb:color2}
focused 		= ${xrdb:color3}
unfocused 		= ${xrdb:color3}
icon 			= ${xrdb:color5}


; vim:ft=dosini

